#lang scheme
; Exercise 1.15 
; The sine of an angle (specified in radians) can be
; computed by making use of the approximation sin x ≈ x if x is
; sufficiently small, and the trigonometric identity
; sin x = 3sin(x/3) - 4sin^3(x/3)
; to reduce the size of the argument of sin.

(define cube (λ(x) (* x x x)))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

; Questions
; ---------
; a) How many times is the procedure p applied when (sine 12.15)
; is evaluated?
; Lets take a look at how the process executes. 
; (sine 12.15)
; (p (sine 4.05))
; (p (p (sine 1.35)))
; (p (p (p (sine 0.45))))
; (p (p (p (p (sine 0.15)))))
; (p (p (p (p (p (sine 0.05))))))
; (p (p (p (p 0.1495))))
; (p (p (p 0.4351345505)))
; (p (p 0.9758465331678772))
; (p -0.7895631144708228)
; -0.39980345741334
; Hence, p is evaluated 5 times!

; b) What is the order of growth in space and number of 
; steps (as a function of a ) used by the process generated by the 
; sine procedure when (sine a) is evaluated?
; Both complexities are O(log n), as we can triple the input
; before another call is added. 